services:
  - type: web
    name: asw-lab-front
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist -l 3000
    publishDirectory: dist
    envVars:
      - key: NODE_VERSION
        value: 18
